POST http://localhost:3305/outpass 
Content-Type: application/json

{
    "name":"jeevan", 
    "registernumber":"20104035", 
    "email":"jeevenkumar2003@gmail.com", 
    "year":"IV", 
    "department":"CSE", 
    "semester":"VII", 
    "reason":"veetuku poganum"
}



