POST http://localhost:3305/outpass 
Content-Type: application/json

{
    "name":"jeevan", 
    "registernumber":"20104035", 
    "email":"jeevenkumar2003@gmail.com", 
    "year":4, 
    "department":"CSE", 
    "semester":"7", 
    "reason":"veetuku poganum"
}

###
GET http://localhost:3305/history/20104060 
