POST http://localhost:3305/outpass2
Content-Type: application/json

{
    "name":"jeevan", 
    "registernumber":"2K21CA036", 
    "email":"jeevenkumar2003@gmail.com", 
    "year":"IV", 
    "department":"CSE", 
    "semester":"VII", 
    "reason":"veetuku poganum"
}


###
POST http://localhost:3305/outpass2/c21f8328-289c-4168-8596-dcb49e1487bb/accept

###
POST http://localhost:3305/register2 
Content-Type: application/json

{
    "username":"2K21CA04",
    "password":"arunjk",
    "user":"student"
}
###
POST http://localhost:3305/delete 
Content-Type: application/json

{
    "username":"parimalam"
}

###
POST http://localhost:3305/register 
Content-Type: application/json

{
    "username":"sangeetha",
    "password":"sangeetha",
    "user":"hod"
}
###
POST http://localhost:3305/register 
Content-Type: application/json

{
    "username":"12847",
    "password":"gopinath",
    "user":"student"
}
###
POST http://localhost:3305/register 
Content-Type: application/json

{
    "username":"12847",
    "password":"gopinath",
    "user":"student"
}
###
POST http://localhost:3305/login1
Content-Type: application/json

{
    "username":"deepa",
    "password":"deepa"
}


###
GET http://localhost:3305/history1 
